[[left]]
name = "env"
color.background = "white"
color.foreground = "black"
args = ["user_at_host"]

[[left]]
name = "dir"
color.background = "blue"
color.foreground = "white"

[[left]]
name = "git"
color.background = "green"
color.foreground = "white"

[[left]]
name = "status"
color.background = "red"
color.foreground = "white"
